"""initial migration with ordered columns

Revision ID: 62f711d69ee6
Revises:
Create Date: 2025-04-11 19:09:33.090870

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62f711d69ee6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=True),
        sa.Column("parent_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_category_name"),
        "categories",
        ["category_name"],
        unique=True,
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_id"), "sources", ["id"], unique=False)
    op.create_index(op.f("ix_sources_name"), "sources", ["name"], unique=True)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "dt_created", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "dt_updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("sub_category_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("normalized_description", sa.String(), nullable=True),
        sa.Column(
            "categorization_status",
            sa.Enum("pending", "categorized", "failed", name="categorization_status"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_categorization_status"),
        "transactions",
        ["categorization_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_date"), "transactions", ["date"], unique=False
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_normalized_description"),
        "transactions",
        ["normalized_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_source_id"), "transactions", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_source_id"), table_name="transactions")
    op.drop_index(
        op.f("ix_transactions_normalized_description"), table_name="transactions"
    )
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_date"), table_name="transactions")
    op.drop_index(
        op.f("ix_transactions_categorization_status"), table_name="transactions"
    )
    op.drop_table("transactions")
    op.drop_index(op.f("ix_sources_name"), table_name="sources")
    op.drop_index(op.f("ix_sources_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_category_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
