"""add statement and statement schema tables

Revision ID: 7ec307fd117b
Revises: 62f711d69ee6
Create Date: 2025-04-14 14:34:22.345109

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7ec307fd117b"
down_revision = "62f711d69ee6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statements",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_statements_id"), "statements", ["id"], unique=True)

    op.create_table(
        "statement_schemas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("statement_id", sa.String(), nullable=True),
        sa.Column("column_hash", sa.String(), nullable=False),
        sa.Column(
            "column_mapping", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statement_schemas_column_hash"),
        "statement_schemas",
        ["column_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_statement_schemas_id"), "statement_schemas", ["id"], unique=False
    )

    op.add_column("transactions", sa.Column("statement_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "transactions", "statements", ["statement_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "statement_id")
    op.drop_index(op.f("ix_statement_schemas_id"), table_name="statement_schemas")
    op.drop_index(
        op.f("ix_statement_schemas_column_hash"), table_name="statement_schemas"
    )
    op.drop_table("statement_schemas")
    op.drop_index(op.f("ix_statements_id"), table_name="statements")
    op.drop_table("statements")
    # ### end Alembic commands ###
