"""Add normalized_description to Transaction

Revision ID: 836154eb6995
Revises: 25188a7e8dba
Create Date: 2025-04-05 16:03:59.120614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836154eb6995'
down_revision = '25188a7e8dba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('normalized_description', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_normalized_description'), 'transactions', ['normalized_description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_normalized_description'), table_name='transactions')
    op.drop_column('transactions', 'normalized_description')
    # ### end Alembic commands ###
