"""rename_column_hash_to_statement_hash_and_simplify_schema

Revision ID: 85a74cd6fd3a
Revises: 7ec307fd117b
Create Date: 2025-04-14 16:50:49.803625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85a74cd6fd3a'
down_revision = '7ec307fd117b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_schemas', sa.Column('statement_hash', sa.String(), nullable=True))
    op.add_column('statement_schemas', sa.Column('schema', sa.JSON(), nullable=False))
    op.drop_index('ix_statement_schemas_column_hash', table_name='statement_schemas')
    op.create_index(op.f('ix_statement_schemas_statement_hash'), 'statement_schemas', ['statement_hash'], unique=True)
    op.drop_constraint('statement_schemas_source_id_fkey', 'statement_schemas', type_='foreignkey')
    op.drop_column('statement_schemas', 'file_type')
    op.drop_column('statement_schemas', 'column_mapping')
    op.drop_column('statement_schemas', 'column_hash')
    op.drop_column('statement_schemas', 'source_id')
    op.drop_index('ix_statements_id', table_name='statements')
    op.create_index(op.f('ix_statements_id'), 'statements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statements_id'), table_name='statements')
    op.create_index('ix_statements_id', 'statements', ['id'], unique=True)
    op.add_column('statement_schemas', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('statement_schemas', sa.Column('column_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('statement_schemas', sa.Column('column_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('statement_schemas', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('statement_schemas_source_id_fkey', 'statement_schemas', 'sources', ['source_id'], ['id'])
    op.drop_index(op.f('ix_statement_schemas_statement_hash'), table_name='statement_schemas')
    op.create_index('ix_statement_schemas_column_hash', 'statement_schemas', ['column_hash'], unique=True)
    op.drop_column('statement_schemas', 'schema')
    op.drop_column('statement_schemas', 'statement_hash')
    # ### end Alembic commands ###
