"""Add categorization_status to Transaction model

Revision ID: b6d9462d609f
Revises: 836154eb6995
Create Date: 2025-04-08 18:28:06.616574

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6d9462d609f"
down_revision = "836154eb6995"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "categorization_status",
            sa.Enum("pending", "categorized", "failed", name="categorization_status"),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_transactions_categorization_status"),
        "transactions",
        ["categorization_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transactions_categorization_status"), table_name="transactions"
    )
    op.drop_column("transactions", "categorization_status")
    # ### end Alembic commands ###
