"""add source_id to transactions

Revision ID: e902f1403a16
Revises: 4796b9d1bcd8
Create Date: 2025-04-05 15:08:58.651653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e902f1403a16'
down_revision = '4796b9d1bcd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('source_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_source_id'), 'transactions', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_source_id'), table_name='transactions')
    op.drop_column('transactions', 'source_id')
    # ### end Alembic commands ###
