"""Rename statement_schemas table to statement_schema_mappings and drop statement_id column

Revision ID: ec6da67186a0
Revises: a1bcfeccb55c
Create Date: 2025-04-15 17:33:38.634249

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec6da67186a0'
down_revision = 'a1bcfeccb55c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('statement_schemas', 'statement_schema_mappings')
    # If the column exists, drop it
    with op.batch_alter_table('statement_schema_mappings') as batch_op:
        batch_op.drop_column('statement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('statement_schema_mappings', 'statement_schemas')
    with op.batch_alter_table('statement_schemas') as batch_op:
        batch_op.add_column(sa.Column('statement_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('statement_schemas_statement_id_fkey', 'statements', ['statement_id'], ['id'])
    # ### end Alembic commands ###
