"""add_sub_category_id_to_transactions

Revision ID: f00b69df99ba
Revises: b6d9462d609f
Create Date: 2025-04-11 17:20:27.915954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00b69df99ba'
down_revision = 'b6d9462d609f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'categories', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'sub_category_id')
    # ### end Alembic commands ###
